### ISSUE TITLE
The plugin seems to conflict with vim-lastplace plugin

### ISSUE THREAD

**Issue by sergei-mironov** [TamaMcGlinn/vim-bettergf#2]
In my setup, jumping to the file:line seems to work, but `<C-o>` does not. Pressing `<C-o>` does not bring me back to the original file. Instead, it opens the location which would be opened by the vim-lastplace plugin.

**Comment by TamaMcGlinn** [comment]
I installed vim-lastplace to examine the behaviour, but I can't see what is wrong. Please give exact steps, e.g.

Given README.md with at least 10 lines, and a terminal split below, do `echo 'README.md:8'` in the terminal, and then `echo 'README.md:2'`, so that we have two lines we can jump to using `gf` in normal mode in the terminal.

Then give me some expected versus actual behaviour for where it jumps to. As far as I can see, vim-lastplace only changes where the file is initially opened, and centers the view vertically. Then each jump with bettergf adds something to the jumplist, and `<C-o>` and `<C-i>` cycle through the list as expected. The vim-lastplace plugin also adds one location, but only once upon opening the file.

**Comment by sergei-mironov** [comment]
Thank you for the response! Let's first address the TermOpen issue in #1 I think it could be the cause.

**Comment by sergei-mironov** [comment]
I could not reproduce it any more, so I think I need to close this one as well. Thanks!
